spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: insert_data.sql
      schema-locations: init.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true


#logging:
#  level:
#    root: INFO